// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"projectlayout/app/cmd/album/internal/conf"
	"projectlayout/app/cmd/album/internal/data"
)

// Injectors from wire.go:

func InitSetting() interface{} {
	error2 := InitConf()
	v := InitDB(error2)
	return v
}

// wire.go:

func InitConf() error {
	err := conf.Init(flagconf)
	return err
}

func InitDB(err error) interface{} {
	if err != nil {
		panic(err)
	}
	if err = data.InitDB(); err != nil {
		panic(err)
	}
	return nil
}
